name: jumpbox-website
run-name: Jumpbox Website Pipeline

on:
  push:
    branches:
      - develop

jobs:
  develop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    container:
      image: docker:24.0.2-git
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
            apk add --update nodejs npm zip aws-cli

      - name: Node vesrion
        run: |
            echo "Node version: " $(node -v)
            echo "NPM version: " $(npm -v)

      - name: Zip vesrion
        run: |
            echo "Zip version: " 
            zip -v

      - name: AWS CLI vesrion
        run: |
            echo "AWS CLI version: " $(aws --version)

      - name: Reload Environments
        run: |
          echo "COMMIT_ID=${GITHUB_SHA} >> $GITHUB_ENV
            
      - name: Commit ID
        run: |
            echo "COMMIT_ID: " ${{ env.COMMIT_ID }}

      - name: Install Dependencies
        run: |
            npm install
            npm run generate
            echo "\n\n====== GENERATE OUTPUT ======"
            ls .output/public
            echo "\n\n============================="

      - name: Package Artifact
        run: |
            cd .output/public
            zip -r /tmp/${{ env.COMMIT_ID }}.zip .
            ls /tmp/${{ env.COMMIT_ID }}.zip

      - name: Upload Artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: | 
            aws s3 ls
            aws s3 sync /tmp/${{ env.COMMIT_ID }}.zip s3://${{ secrets.S3_BUCKET_DEV_ARTIFACT }}

      - name: Deploy
        run: |
          cd .output/public
          aws s3 sync . s3://${{ secrets.S3_BUCKET_DEV }}