name: jumpbox-website-prod
run-name: Jumpbox Website Pipeline Deploy Production

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' 

jobs:
  deploy-with-tag:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    container:
      image: docker:24.0.2-git
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Install Tools
        run: |
            apk add --update zip aws-cli

      - name: Zip vesrion
        run: |
            echo "Zip version: " 
            zip -v

      - name: AWS CLI vesrion
        run: |
            echo "AWS CLI version: " $(aws --version)

      - name: Reload Environments
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            
      - name: RELEASE_VERSION
        run: |
            echo "RELEASE_VERSION: " ${{ env.RELEASE_VERSION }}

      - name: Download Package Artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
            mkdir -p /tmp/release
            aws s3 cp s3://${{ secrets.S3_BUCKET_PROD_ARTIFACT }}/${{ env.RELEASE_VERSION }}.zip /tmp/release

      - name: Extract
        run: | 
            unzip /tmp/release/${{ env.RELEASE_VERSION }}.zip

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cd /tmp/release
          unzip ${{ env.RELEASE_VERSION }}.zip
          rm ${{ env.RELEASE_VERSION }}.zip
          aws s3 sync . s3://${{ secrets.S3_BUCKET_PROD }}
          
      - name: Flush the CDN Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_PROD }} --paths "/*"
